
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: May 25 2026 11:24:14 CDT (May 25 2026 16:24:14 UTC)

// Verification Directory fv/transition_detector 

module transition_detector(clk, rstb, in, out);
  input clk, rstb, in;
  output out;
  wire clk, rstb, in;
  wire out;
  wire Q1, UNCONNECTED, UNCONNECTED0, n_0, n_9;
  DFFR_X1 Q0_reg(.RN (rstb), .CK (clk), .D (n_0), .Q (out), .QN
       (UNCONNECTED));
  XNOR2_X1 g19__8780(.A (n_9), .B (Q1), .ZN (n_0));
  DFFR_X1 Q1_reg(.RN (rstb), .CK (clk), .D (n_9), .Q (UNCONNECTED0),
       .QN (Q1));
  CLKBUF_X1 drc_buf_sp(.A (in), .Z (n_9));
endmodule

